### ISSUE TITLE
Build Failed - No such Module ArWebView

### ISSUE THREAD

**Issue by kkadapa** [google/iosched-ios#5]
Despite following the README instructions I get the following error...

![image](https://user-images.githubusercontent.com/6679852/90970539-6f50fe00-e4d4-11ea-9b86-8fa721f0475f.png)

Did I make any mistake during the installation? how can I resolve this error?

**Comment by morganchen12** [comment]
Hey @kkadapa, currently IOSched iOS is missing several closed-source components required to build. The closed-source components are owned by other teams and they're not considering open-sourcing them at this time.
